apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: broker
  name: broker
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: confluentinc/cp-server:6.0.1
    generation: null
    importPolicy: {}
    name: 6.0.1
status:
  dockerImageRepository: ""
