apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: control-center
  name: control-center
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: confluentinc/cp-enterprise-control-center:6.0.1
    generation: null
    importPolicy: {}
    name: 6.0.1
status:
  dockerImageRepository: ""
