apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: F:\kafka\kompose\kompose.exe convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: ksqldb-server
  name: ksqldb-server
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    io.kompose.service: ksqldb-server
status:
  loadBalancer: {}
