apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: F:\kafka\kompose\kompose.exe convert --provider=openshift
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: schema-registry
  name: schema-registry
spec:
  replicas: 1
  selector:
    io.kompose.service: schema-registry
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: schema-registry
    spec:
      containers:
      - env:
        - name: KAFKA_HEAP_OPTS
          value: -Xmx128M -Xms128M
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: schema-registry
        - name: SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS
          value: broker:29092
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://0.0.0.0:8081
        image: ' '
        name: schema-registry
        ports:
        - containerPort: 8081
        resources: {}
      hostname: schema-registry
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - schema-registry
      from:
        kind: ImageStreamTag
        name: schema-registry:6.0.1
    type: ImageChange
status: {}
